# 环境
language: node_js

cache:
  apt: true
  directories:
    - node_modules

before_install:
  - npm install -g npm@2

# 安装阶段
install:
  - npm install

# 脚本运行
script:
  - npm run lint
  - npm rum test
